apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 5000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
